enum
{
    // string table definitions
    IDS_VOLUME_OBJECT   = 10000,
    IDS_VOLUME_OBJECT_BUBBLE_HELP,
    IDS_VOLUME_RENDERER,
    IDS_VOLUME_RENDERER_BUBBLE_HELP,
    IDS_VOLUME_TAG,
    IDS_VOLUME_TAG_BUBBLE_HELP,
    IDS_LOADING_SIMULATION_FRAME,
    IDS_ILLUMINATING_VOLUME,
    IDS_SIMULATING,

    IDS_TRB4D_EXCEPTION,
    IDS_TRB4D_HINT,
    IDS_FAILED_TO_OPEN_CACHE,
    IDS_FAILED_TO_MOVE_CACHE,
    IDS_DELETE_TEMPORARY_CACHE,
    IDS_CHOOSE_DIFFERENT_DIR,
    IDS_CHOOSE_DIFFERENT_DIR_OR_TEMP,
    IDS_OVERWRITE_CACHE_DIR,
    IDS_COPYING_FILES,

    IDS_SIMULATION_DIALOG_TITLE_PREFIX,
    IDS_ABORT,
    IDS_START,
    IDS_STOP,
    IDS_REFRESH,
    IDS_AUTO_REFRESH,
    IDS_FRAME,
    IDS_ELAPSED,
    IDS_ESTIMATED,
    IDS_SIMULATION_OCCUPIED,
    IDS_ABORT_SIMULATION_SHORT,
    IDS_ABORT_SIMULATION_LONG,
    IDS_FINISHED,
    IDS_ABORTED,
    IDS_BETA_LIMITATION,
    IDS_RESOLUTION_TOO_LARGE,
    IDS_SIM_MEMORY,
    IDS_CACHE_MEMORY,
    IDS_DISK_MEMORY,

    IDS_LICENSED_TO,
    IDS_DEMO_VERSION,
    IDS_EARLY_BIRD,
    IDS_TURBULENCE4D_VERSION,
    IDS_RENDER_WHEN_DONE,
    IDS_SIMULATION_TOOL,
    IDS_NO_VOLUME_SELECTED_SHORT,
    IDS_NO_VOLUME_SELECTED_LONG,
    IDS_FAILED_TO_LOAD_SIM_STATE_SHORT,
    IDS_FAILED_TO_LOAD_SIM_STATE_LONG,
    IDS_T4D_PREF_DIALOG,
    IDS_DEFAULT_CACHE_BASE_PATH,

    IDS_GETFLUIDDATA_NODE,
    IDS_TURBULENCE4D,
    IDS_PFLUID_NODE,

    IDS_NEW,
    IDS_RENAME,
    IDS_REMOVE,
    IDS_BROWSE,
    IDS_CONFIRM_REMOVE_CACHE_TITLE,
    IDS_CONFIRM_REMOVE_CACHE_BODY,
    IDS_CHECK_FOR_UPDATE,
    IDS_SAVE_PROJECT_ON_SIM,

    IDS_UPDATE_TIMELINE,

    IDS_NO_CACHE_FRAME_AVAILABLE,

    IDS_HELP_TOOL,
    IDS_UPDATE_AVAILABLE,
    IDS_AUTO_CHECK_UPDATE,
    IDS_NO_UPDATE_AVAILABLE,
    IDS_USING_LATEST_VERSION,
    IDS_PURCHASE_TOOL,
    IDS_PURCHASE_BUTTON,
    IDS_UPDATE_CHECK_TOOL,

    IDS_PREVIEW_DIALOG_TITLE_PREFIX,
    IDS_PREVIEW_TOOL,

    IDS_SF_OPACITY_DISPLAY,
    IDS_SSS_INTENSITY_DISPLAY,
    IDS_SFCS_INTENSITY_DISPLAY,

    IDS_SETFLUIDDATA_NODE,

    IDS_NETRENDER_NOT_SUPPORTED,
    IDS_PREPARING_SIMULATION_FRAME,

    IDS_PARTICLE_PROPERTY_MAPPING_DISPLAY,

    IDS_OUTPUT_SRGB,

    IDS_VELNOISE_INTENSITY_DISPLAY,

    IDS_SAVE_SIM_STATE_TITLE,
    IDS_SAVE_SIM_STATE,
    IDS_FINISHING,
    IDS_CONTINUE,
    IDS_OVERWRITE_CACHE_TITLE,
    IDS_OVERWRITE_CACHE,
    IDS_UPRES,

    IDS_NO_VEL_IN_CACHE_TITLE,
    IDS_NO_VEL_IN_CACHE,

    IDS_CANT_START_SIM_WHILE_RENDER_SHORT,
    IDS_CANT_START_SIM_WHILE_RENDER_LONG,

    IDS_FUELMASK_DISPLAY,

    IDS_CACHE_LOCKED_SHORT,
    IDS_CACHE_LOCKED_LONG,

    IDS_LICENSE_SERVER_CONNECTION_FAILED_SHORT,
    IDS_LICENSE_SERVER_CONNECTION_FAILED_LONG,

    IDS_MULTIPLE_SCATTERING,
    IDS_SIM_MEM_MAY_BE_TOO_BIG_SHORT,
    IDS_SIM_MEM_MAY_BE_TOO_BIG_LONG,
    IDS_SIM_MEM_MAY_BE_TOO_BIG_LONG2,
    IDS_SIM_MEM_MAY_BE_TOO_BIG_LONG3,

    IDS_RESOLUTION_INFO_FORMAT,

    IDS_SS_OPACITY_DISPLAY,

    IDS_LICENSE_SERVER_ACTIVATION_FAILED_SHORT,
    IDS_LICENSE_SERVER_ACTIVATION_FAILED_LONG,

    IDS_DIST_OPAQ_MAPPING_DISPLAY,
    IDS_CONTINUE_TOOL,
    IDS_UPRES_TOOL,

    IDS_ASK_BEFORE_OVERWRITING_CACHE,

    IDS_NO,
    IDS_YES,
    IDS_OK,
    IDS_CANCEL,
    IDS_CREATE,

    IDS_USE_CPU,
    IDS_USE_GPU,

    IDS_OPEN_SIM_DIALOG_TOOL,
    IDS_FPS_MISMATCH,
    IDS_FPS_MISMATCH_TITLE,
    IDS_NO_NETRENDER_IN_LE,
    IDS_FAILED_TO_REMOVE_CACHE_DIR_TITLE,
    IDS_FAILED_TO_REMOVE_CACHE_DIR,

    IDS_SCENE_NOT_SUPPORTED_TITLE,
    IDS_SCENE_NOT_SUPPORTED,

    IDS_UPDATE_CHECK_FAILED,
    IDS_UPDATE_CHECK_FAILED_LONG,

    IDS_MB_LENGTH,
    IDS_MB_SUBSTEPS,

    IDS_VORTICITY_INTENSITY_DISPLAY,

    IDS_INCOMPATIBLE_CUDA_DRIVER,
    IDS_INCOMPATIBLE_CUDA_DRIVER_TITLE,
    IDS_SIMULATION_EXCEPTION_TITLE,
    IDS_SIMULATION_EXCEPTION,
    IDS_SIMULATION_EXCEPTION2,
    IDS_SIMULATION_EXCEPTION3,

    IDS_SIM_MODE_BACKGROUND,
    IDS_SIM_MODE_INTERACTIVE,
    IDS_SIM_MODE_UPRES,

    IDS_INTERACTIVE_SIM_TOOL,
    IDS_STOP_SIM_TOOL,

    IDS_ALT_BASE_PATH,
    IDS_GPU_VOLUME_RENDERER,

    IDS_ADVECT_METHOD_FINVOL,

    IDS_INSUFFICIENT_XPARTICLES_VERSION,
    IDS_INSUFFICIENT_XPARTICLES_VERSION_TITLE,

    IDS_SCENE_RESTRICTED_TITLE,
    IDS_SCENE_RESTRICTED,

    // End of symbol definition
    _DUMMY_ELEMENT_
};
