CONTAINER GVsetfluiddata
{
    NAME GVsetfluiddata;
    INCLUDE GVbase;

    GROUP ID_GVSFD_PROPERTIES
    {
        GVGENERALOBJECT GVSFD_VOLUME_OBJECT {INPORT; NEEDCONNECTION; CREATEPORT;}
        VECTOR GVSFD_POSITION {INPORT; NEEDCONNECTION;}

        VECTOR GVSFD_VELOCITY {OUTPORT;}
        REAL GVSFD_TEMPERATURE {OUTPORT;}
        REAL GVSFD_DENSITY {OUTPORT;}
        REAL GVSFD_FUEL {OUTPORT;}
        REAL GVSFD_FIRE {OUTPORT;}
    }
}
