CONTAINER Pfluid
{
    NAME Pfluid;
    INCLUDE GVbase;

    GROUP ID_PFLD_PROPERTIES
    {
        GVGENERALOBJECT PFLD_VOLUME_OBJECT {INPORT; NEEDCONNECTION; CREATEPORT;}
        TP_PARTICLE PFLD_PARTICLE {INPORT; NEEDCONNECTION; CREATEPORT;}
        REAL PFLD_SCALE {INPORT;}
        BOOL PFLD_SET_SPIN {INPORT;}
        REAL PFLD_SPIN_SCALE {INPORT;}
        BOOL PFLD_ADD_NOISE {INPORT;}
    }
}
