#ifndef _PTURBULENCEFD_H_
#define _PTURBULENCEFD_H_

enum
{
    ID_TURBULENCEFD_PREFS_MAIN_GROUP = 999,
    ID_DEFAULT_CACHE_BASE_PATH = 1000,
    ID_SAVE_PROJECT_ON_SIM,
    ID_AUTO_CHECK_UPDATE,
    ID_ALWAYS_SAVE_STATE,
    ID_ASK,
    ID_ALWAYS,
    ID_NEVER,
    ID_ASK_BEFORE_OVERWRITING_CACHE,
};

#endif
