CONTAINER PTurbulenceFD
{
    NAME PTurbulenceFD;

    GROUP ID_TURBULENCEFD_PREFS_MAIN_GROUP
    {
        DEFAULT 1;

        FILENAME ID_DEFAULT_CACHE_BASE_PATH
        { DIRECTORY; }
        BOOL ID_SAVE_PROJECT_ON_SIM {}
        BOOL ID_AUTO_CHECK_UPDATE {}
        BOOL ID_ASK_BEFORE_OVERWRITING_CACHE {}
    }
}
