#ifndef _Tvolume_H_
#define _Tvolume_H_

enum
{
    ID_DENSITY = 1001,
    ID_TEMPERATURE,
    ID_OBSTACLE,
    ID_FUEL,
    ID_NORMAL_FORCE,
    ID_SELECTION_LIST,
    ID_FLAME,
    ID_VOXELIZATION_MODE,
    ID_VOXMODE_SMOOTH,
    ID_VOXMODE_BOXED,
    ID_VOXMODE_FILL_SMOOTH,
    ID_VOXMODE_FILL_BOXED,
    ID_VOXELIZATION_RADIUS,
    ID_ADD_NOISE,
    ID_NOISE_FREQ,
    ID_NOISE_OFFSET,
    ID_NOISE_SPEED,
    ID_NOISE_INTENSITY,
    ID_VOXMODE_NOISE,
    ID_VOXELIZATION_FILL,
    ID_NOISE_DETAIL,

    ID_TAG_EMITTER,
    ID_TAG_SURFACE,
    ID_TAG_TURBULENCE,
    ID_INDUCE_TURBULENCE,
    ID_OBJVELNOISE_RADIUS,
    ID_OBJVELNOISE_INTENSITY,
    ID_OBJVELNOISE_FREQ,
    ID_OBJVELNOISE_DETAIL,
    ID_OBJVELNOISE_SPEED,
    ID_OBJVELNOISE_OFFSET,
    ID_DIVERGENCE,
    ID_VOXELIZATION,

    ID_TAG_GENERAL,
    ID_DIR_FORCE,

    ID_DENSITY_GROUP,
    ID_TEMPERATURE_GROUP,
    ID_FUEL_GROUP,
    ID_DENSITY_MODE,
    ID_TEMPERATURE_MODE,
    ID_FUEL_MODE,
    ID_SOURCE_MODE_ADD,
    ID_SOURCE_MODE_SET,

    ID_TAGPARAMETER_VERSION,

    ID_TAG_PARTICLE_DECAY,
    ID_EMITTER_VELOCITY_WEIGHT,
    ID_TAG_SHADER,

    ID_FORCE_GROUP,
    ID_PARTICLE_GROUP,
    ID_PARTICLE_PROPERTY,
    ID_PARTICLE_PROPERTY_MAPPING,
    ID_PART_PROP_NONE,
    ID_PART_PROP_AGE,
    ID_PART_PROP_VEL,
    ID_PART_PROP_MAS,
    ID_PART_PROP_SIZ,

    ID_EMITTER_ACTIVE,
    ID_USE_VERTEX_MAPS,
    ID_TEXTURE_CHANNEL,
    ID_TEXTURE_CHANNEL_NONE,
    ID_TEXTURE_CHANNEL_LUMINANCE,
    ID_TEXTURE_CHANNEL_TRANSPARENCY,
    ID_TEXTURE_CHANNEL_ALPHA,
    ID_TEXTURE_CHANNEL_COLOR,

    ID_CHANNELS_GROUP,
    ID_BURN_MODE,
    ID_BURN,

    ID_GENERAL_GROUP,
    ID_TEXTURE_GROUP,
};

#endif
