#ifndef _VPvolume_H_
#define _VPvolume_H_

enum
{
    ID_OUTPUT_SRGB = 1001,
    ID_VPMAIN,
    ID_RAY_STEP_ADAPTIVE,
    ID_ADAPTIVE_THRESHOLD,
    ID_MB_LENGTH,
    ID_MB_SUBSTEPS,
    ID_USE_FLUID_MOTION_BLUR,
    ID_DISTRIBUTE_CACHE_TO_TR_CLIENTS,
};

#endif
